# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  pod 'RxSwift',    '~> 4.0'
  pod 'OpenTok',    '~> 4.0'

end
